# What is NumPy?

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and we can use it freely.

NumPy stands for Numerical Python.

# Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

# Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

# Which Language is NumPy written in?

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

# Numpy

In [1]:
import numpy as np

# Array

In [6]:
array=np.array([1,2,3,4,5])

In [7]:
array

array([1, 2, 3, 4, 5])

In [8]:
type(array)

numpy.ndarray

In [13]:
#check the dimension
np.ndim(array)

1

In [10]:
array2=np.array([[1,2,3,4,5]])
print(array2)

[[1 2 3 4 5]]


In [12]:
print(type(array))
print(np.ndim(array2))

<class 'numpy.ndarray'>
2


In [15]:
array= np.array([10,20,30,40,60], ndmin=5)
array

array([[[[[10, 20, 30, 40, 60]]]]])

In [16]:
l=[[[1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5]],
   
   [[1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5]]]


In [17]:
arr=np.array(l)
arr

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [18]:
np.ndim(arr)

3

# Asarray

In [19]:
np.asarray(l, order="C")

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [23]:
np.asarray(l) is np.asarray(l) 

False

In [20]:
#AS any array
np.asanyarray(l) #create array subclass 

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [21]:
np.asanyarray(l) is l

False

In [22]:
np.asanyarray(l) is np.asanyarray(l)

False

# functional numpy

In [25]:
np.fromfunction(lambda i, j: i==j, (3,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
[[1==1,1==2,1==3],
 [2==1,2==2,1==3],
 [3==1,3==2,3==3]]

[[True, False, False], [False, True, False], [False, False, True]]

# list comprehentions

In [30]:
[x for x in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
i=[x for x in range(10)]

# dictionary comprehentions


In [31]:
{x:x for x in range(10)}

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9}

In [37]:
{x:x*x for x in range(1,10)}

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [38]:
dict={
    0:1,
    1:2,
    2:3,
    3:4,
}
{x:y for x,y in dict.items()}

{0: 1, 1: 2, 2: 3, 3: 4}

In [40]:
np.fromiter(i,dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
np.fromiter(i,dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
str_val="1,2,3,4,5,6,7,8,10"
np.fromstring(str_val, dtype=int, sep=',')

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [63]:
import re
str_val2="1,2-3,4,5-6,7,8,9,10-11,12,13,14,15,16"
#np.fromstrig(str_val2,dtype=int,sep="','or '-'")


str_=re.split(',|-',str_val2)
print(str_)
np.array(str_,dtype=int)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [45]:
l=[[[1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5]],
   
   [[1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5]]]
arr=np.array(l)
arr

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [46]:
arr.size

30

In [47]:
arr.shape

(2, 3, 5)

# numpy arrange


In [68]:
a=np.arange(0,100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [69]:
a.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [74]:
a.resize(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [75]:
arr=np.array(a)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [76]:
arr.resize(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [79]:
one_values=np.ones(100, dtype=int)

In [80]:
one_values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [81]:
one_values + 10

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [19]:
zero=np.zeros(100)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
zero+100

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100.])

In [21]:
zero.resize(10,10)

In [22]:
print(zero)
zero.ndim


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


2

# slice

In [ ]:
a=np.arange(1,11)
print("\n",a)

In [49]:
print("\n",a[:])
print("\n",a[2:6])
print("\n",a[1:7:5])
print("\n",a[0],a[2])


 [ 1  2  3  4  5  6  7  8  9 10]

 [3 4 5 6]

 [2 7]

 1 3


In [23]:

zero[3:6,3:7]=1

In [24]:
zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
zero[6:10,6:10]=2

In [26]:
zero=np.asarray(zero, dtype=int)

In [27]:
zero[3,7]=4

In [28]:
zero

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 4, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2]])

In [31]:
zero[0,3:7]=3
zero

array([[0, 0, 0, 3, 3, 3, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 4, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2]])

In [32]:
zero[1,3:7]=8
zero

array([[0, 0, 0, 3, 3, 3, 3, 0, 0, 0],
       [0, 0, 0, 8, 8, 8, 8, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 4, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2]])

In [33]:
zero[1:6,9]=6
zero

array([[0, 0, 0, 3, 3, 3, 3, 0, 0, 0],
       [0, 0, 0, 8, 8, 8, 8, 0, 0, 6],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 6],
       [0, 0, 0, 1, 1, 1, 1, 4, 0, 6],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 6],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 6],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 2, 2, 2, 2]])

In [34]:
zero[6:9,3:6]=[[75,866,977],[1,5,9],[3,5,7]]
zero

array([[  0,   0,   0,   3,   3,   3,   3,   0,   0,   0],
       [  0,   0,   0,   8,   8,   8,   8,   0,   0,   6],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   6],
       [  0,   0,   0,   1,   1,   1,   1,   4,   0,   6],
       [  0,   0,   0,   1,   1,   1,   1,   0,   0,   6],
       [  0,   0,   0,   1,   1,   1,   1,   0,   0,   6],
       [  0,   0,   0,  75, 866, 977,   2,   2,   2,   2],
       [  0,   0,   0,   1,   5,   9,   2,   2,   2,   2],
       [  0,   0,   0,   3,   5,   7,   2,   2,   2,   2],
       [  0,   0,   0,   0,   0,   0,   2,   2,   2,   2]])

In [35]:
zero[4:6,4:6]=[[100,200],[300,400]]

In [36]:
zero

array([[  0,   0,   0,   3,   3,   3,   3,   0,   0,   0],
       [  0,   0,   0,   8,   8,   8,   8,   0,   0,   6],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   6],
       [  0,   0,   0,   1,   1,   1,   1,   4,   0,   6],
       [  0,   0,   0,   1, 100, 200,   1,   0,   0,   6],
       [  0,   0,   0,   1, 300, 400,   1,   0,   0,   6],
       [  0,   0,   0,  75, 866, 977,   2,   2,   2,   2],
       [  0,   0,   0,   1,   5,   9,   2,   2,   2,   2],
       [  0,   0,   0,   3,   5,   7,   2,   2,   2,   2],
       [  0,   0,   0,   0,   0,   0,   2,   2,   2,   2]])

In [47]:
print("\n",zero[0:2,3])
print("\n",zero[[3,7]])# 3 and  7 number rows
print("\n",zero[[4,5,7],[4,5,5]])


 [3 8]

 [[0 0 0 1 1 1 1 4 0 6]
 [0 0 0 1 5 9 2 2 2 2]]

 [100 400   9]


In [136]:
zero.transpose() # Row will colmun and column will row

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  8,   3,   0,   1,   1,   1,  75,   1,   3,   0],
       [  8,   3,   0,   1, 100, 300, 866,   5,   5,   0],
       [  8,   3,   0,   1, 200, 400, 977,   9,   7,   0],
       [  8,   3,   0,   1,   1,   1,   2,   2,   2,   2],
       [  0,   0,   0,   4,   0,   0,   2,   2,   2,   2],
       [  0,   0,   0,   0,   0,   0,   2,   2,   2,   2],
       [  0,   6,   6,   6,   6,   6,   2,   2,   2,   2]])

In [138]:
random=np.random.rand(3,3)
random

array([[0.81941856, 0.13694779, 0.9354924 ],
       [0.4567373 , 0.67969632, 0.33909155],
       [0.80699536, 0.0312347 , 0.88228483]])

In [144]:
np.random.randint(1,10,(10,10))

array([[9, 2, 3, 8, 5, 3, 1, 8, 2, 9],
       [4, 9, 3, 7, 1, 2, 2, 9, 2, 3],
       [9, 7, 6, 2, 5, 7, 4, 4, 5, 1],
       [4, 2, 3, 3, 8, 1, 4, 1, 8, 8],
       [9, 2, 1, 3, 7, 4, 7, 1, 2, 3],
       [6, 3, 4, 1, 9, 5, 7, 8, 3, 8],
       [9, 7, 4, 6, 9, 5, 8, 1, 7, 5],
       [4, 4, 4, 8, 4, 2, 4, 8, 7, 7],
       [5, 4, 5, 6, 8, 2, 1, 6, 4, 7],
       [8, 6, 8, 3, 8, 4, 8, 9, 2, 9]])

In [146]:
np.random.randn(4,4)#standard normal" distribution.

array([[ 0.08378074, -0.80367424, -1.42246271,  1.65294968],
       [ 0.61756901,  0.46785802,  0.17941606,  0.52808907],
       [-0.94011026,  1.27646134, -0.06753862,  1.89402281],
       [ 0.21448653,  1.54395149,  0.67331488, -0.80722777]])

In [195]:
z=np.zeros(100, dtype=int).reshape(10,10)

In [196]:
z

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [197]:
z=np.asarray(z ,dtype=float) #or z=z.astype("float")
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [198]:
z[4:6,4:6]= np.NaN

In [199]:
z

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., nan, nan,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., nan, nan,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [202]:
print(np.isnan(z))
z[np.isnan(z)]

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False  True  True False False False False]
 [False False False False  True  True False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]


array([nan, nan, nan, nan])

In [204]:
# for i in np.nditer(z):
#     print(i)

In [210]:
z[:]=0

In [211]:
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [212]:
z[:]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [213]:
z[...]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# Math term

In [3]:
x=np.array([0,30,45,60,90],dtype=float)
x

array([ 0., 30., 45., 60., 90.])

In [4]:
#sin
np.sin(x*(np.pi / 180))

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [5]:
#cos
np.cos(x*(np.pi/180))

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [6]:
np.tan(x*(np.pi/180))

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [7]:
np.pi

3.141592653589793

# statistic 

In [8]:
l=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(l)

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print(a.min())
print(a.max())
print(a.mean())

1
9
5.0


In [11]:
a.ptp() #Peak to peak (maximum - minimum)

8

In [12]:
np.percentile(a,9, axis=0)

array([1.54, 2.54, 3.54])

In [13]:
ar=np.array([4,5,6,7,8,9])

In [14]:
ar

array([4, 5, 6, 7, 8, 9])

In [17]:
np.percentile(ar,6)

4.3

In [18]:
ar.max()

9

In [20]:
ar.mean()

6.5

In [22]:
np.median(ar)

6.5

# standard deviation

In [23]:
import math

In [27]:
stdf= np.std(ar)
stdf

1.707825127659933